[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 460800

; TLM922S command UART
build_flags =
  -D TLM_RX_PIN=4
  -D TLM_TX_PIN=5
  -D TLM_BAUD=115200
