[env:seeed_xiao_esp32c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
upload_port = COM[45]
monitor_speed = 115200
monitor_port = COM[45]
monitor_dtr = 1
monitor_rts = 0
upload_speed = 460800

; TLM922S command UART
build_flags =
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D TLM_RX_PIN=20
  -D TLM_TX_PIN=21
  -D TLM_BAUD=115200
